### ISSUE TITLE
RAI dashboard page won't jump out.

### ISSUE THREAD

**Issue by DinaChen** [microsoft/responsible-ai-toolbox#1345]
On Pycharm it shows these two lines after calling _ResponsibleAIDashboard(rai_insights)_, no other error shown. When clicking on the link it says "localhost refused to connect".
---------------------------------------------------------------------------------------------------------------
           **ResponsibleAI started at http://localhost:5000
           Process finished with exit code 0**
----------------------------------------------------------------------------------------------------------------
Then I try to run the code from "responsibleaidashboard-housing-classification-model-debugging.ipynb" both on Pycharm and Jupyter notebook and saw these two lines too:

            ResponsibleAI started at http://localhost:5001/
           <raiwidgets.responsibleai_dashboard.ResponsibleAIDashboard at 0x7f4a9569bd90>
         
What could be the reason that the dashboard page won't jump out?

**Comment by romanlutz** [comment]
Hi @DinaChen! The dashboard requires a running Flask server in the background. As soon as the execution ends the server shuts down and you can't connect to it anymore. In Jupyter notebooks you have the kernel running which keeps it alive. In PyCharm you can also do that, you just need to make sure the execution keeps going. For example, you might prompt for user input so that it doesn't end. I hope that helps!

**Comment by chendingyan** [comment]
I came up with the same issue that both Pycharm and Jupyter notebook won't render RAI dashboard. In jupyter notebook, when i click the link http://localhost:5000, i got HTTP ERROR 403

**Comment by romanlutz** [comment]
Again, in the code you posted initially it seems like the script just finishes. The dashboard is interactive so you need the Python process to keep running otherwise it won't work.

If it's a notebook then make sure the kernel keeps running. I don't know if Pycharm renders it in the IDE itself because I don't use Pycharm. You can certainly open a browser and enter the URL there. Does that work?

**Comment by gaugup** [comment]
@chendingyan, did the workaround that @romanlutz suggested work for you?

**Comment by romanlutz** [comment]
Closing this issue since there's no response. Feel free to reopen if you've tried the suggestion. Please also provide details on your OS, Python version, and relevant Python package versions if you reopen.
