### ISSUE TITLE
RAI Dashboard/Capabilities for Azure ML vs Azure Databricks?

### ISSUE THREAD

**Issue by garimss** [microsoft/responsible-ai-toolbox#1488]
Hi,

I have few questions regarding Responsible AI principals. I will appreciate your help. Please see the questions as listed down below:

1. Is the same applies for Azure Databricks?
2. Is it possible to use it within Azure Databricks?
3. Can export and visualize Azure Databricks Machine Learning Model metric on Responsible AI dashboard?

Just comparing this feature between Azure ML and Azure Databricks.

**Comment by imatiach-msft** [comment]
hi @garimss ,
This repository is OSS and platform agnostic, it should be able to run anywhere, but this question is more geared towards platforms.  First, our individual dashboards can run in both AzureML and Databricks, as well as local compute and competing platforms like AWS, but because Databricks does not allow to open ports we can't enable dynamic functionality like ICE plots and what if analysis.  For the all-in-one Responsible AI dashboard, since it cannot be rendered within notebook it currently does not work on Databricks due to the closed ports issue.  We are exploring the adoption of the entire dashboard for spark in near future however.  Some of our dashboards can even be integrated with distributed spark code (and not just single-node python running on a databricks cluster), for example see:

https://github.com/microsoft/SynapseML/blob/master/notebooks/features/responsible_ai/Interpretability%20-%20Explanation%20Dashboard.ipynb

I also have a working POC for this with the ErrorAnalysisDashboard in Azure Databricks or Azure Synapse (which should be able to work on any spark cluster).  If the code does not work on some platform, it's probably due to limitations in us having the resources to test everywhere possible and not something deliberate, and we certainly welcome any contributions to make our dashboards work on other platforms.
